version: "3"
services: 
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: cse_tutors
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  server:
    build: .
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    
    